# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    sudo apt-get update
    sudo apt-get -y upgrade
    sudo apt-get -y install npm
    npm install
    export NODE_OPTIONS=--openssl-legacy-provider
    yes | npm run prod
    cp -r release/* "$(Build.ArtifactStagingDirectory)"
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'
